server:
  port: 9090
  servlet:
    context-path: /call-dev

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/esl?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  task:
    execution:
      pool:
        # 核心线程数
        core-size: 16
        # 最大线程数
        max-size: 32
        # 队列容量
        queue-capacity: 32
        # 非核心线程最大存活时间
        keep-alive: 60s



mybatis:
  mapper-location: classpath:com/data/call/record/mapper/*.xml
  type-aliases-package: com.data.call.record.dto
  configuration:
    interceptor: com.data.call.mybatis.MybatisSQLInterceptor
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    # 设置MyBatis的日志级别为DEBUG以打印SQL语句
    org.mybatis.spring.SqlSessionFactoryBean: error

    # 针对具体的Mapper接口设置日志级别
    # your.package.to.mappers: TRACE


esl:
  host: 192.168.84.210
  port: 8021
  password: ClueCon
  timeout: 5

