server:
  port: 9090
  servlet:
    context-path: /call_dev

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/esl?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒
      idle-timeout: 300000
      #连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最小空闲连接 默认 0
        max-idle: 8
        # 连接池中的最大空闲连接 默认 8
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 3000
        time-between-eviction-runs: -1

mybatis:
  type-aliases-package: com.data.call.record.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    interceptor: com.data.call.interceptor.mybatis.MybatisSQLInterceptor
  mapper-locations:
    # 扫描mapper,<**>用来匹配多级不定菜单，<*.xml>用来匹配以xml结尾的文件
    - classpath:com/data/call/mapper/**/*.xml

logging:
  level:
    # 设置MyBatis的日志级别为DEBUG以打印SQL语句
    org.mybatis.spring.SqlSessionFactoryBean: error

    # 针对具体的Mapper接口设置日志级别
    # your.package.to.mappers: TRACE


esl:
  host: 192.168.84.210
  port: 8021
  password: ClueCon
  timeout: 5

